# This workflow will do a clean install of node dependencies, build the source code and run tests
name: Node.js CI
permissions:
  contents: write
  packages: write
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    env:
      CI: true
      ESLINT_USE_FLAT_CONFIG: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v5
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test  --if-present
  release:
    name: semantic-release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v5
        with:
          node-version-file: ".nvmrc"
      - run: |
          npm ci
          npx semantic-release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
